### ISSUE TITLE
Project cannot be reloaded when packaged in jar

### ISSUE THREAD

**Issue by wodzuu** [ethlo/lamebda#28] opened 2019-03-26 10:29 UTC
To reproduce:

1. Deploy project from .jar file
2. Verify it works
3. Remove the .jar file
4. Add the .jar file back again

The server hosting the Lamebda framework produces following log:
```
2019-03-26 09:49:12,133  WARN [watch-dir] [com.ethlo.lamebda.FunctionManagerDirector:201] - Unable to load project in /path/gateway/rfc
java.lang.IllegalStateException: java.io.EOFException
	at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:337)
	at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:307)
	at org.springframework.boot.loader.jar.JarFileEntries.doGetEntry(JarFileEntries.java:295)
	at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:248)
	at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:206)
	at org.springframework.boot.loader.jar.JarFile.getEntry(JarFile.java:219)
	at org.springframework.boot.loader.jar.JarFile.getJarEntry(JarFile.java:210)
	at org.springframework.boot.loader.jar.JarURLConnection.connect(JarURLConnection.java:102)
	at org.springframework.boot.loader.jar.JarURLConnection.getJarFile(JarURLConnection.java:112)
	at org.springframework.boot.loader.jar.JarURLConnection.getJarFile(JarURLConnection.java:39)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.doFindPathMatchingJarResources(PathMatchingResourcePatternResolver.java:600)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.findPathMatchingResources(PathMatchingResourcePatternResolver.java:509)
	at org.springframework.core.io.support.PathMatchingResourcePatternResolver.getResources(PathMatchingResourcePatternResolver.java:284)
	at org.springframework.context.support.AbstractApplicationContext.getResources(AbstractApplicationContext.java:1315)
	at org.springframework.context.support.GenericApplicationContext.getResources(GenericApplicationContext.java:235)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:421)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:275)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.scan(ClassPathBeanDefinitionScanner.java:253)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.scan(AnnotationConfigApplicationContext.java:170)
	at com.ethlo.lamebda.FunctionManagerImpl.findBeans(FunctionManagerImpl.java:260)
	at com.ethlo.lamebda.FunctionManagerImpl.initialize(FunctionManagerImpl.java:248)
	at com.ethlo.lamebda.FunctionManagerImpl.<init>(FunctionManagerImpl.java:128)
	at com.ethlo.lamebda.FunctionManagerDirector.create(FunctionManagerDirector.java:184)
	at com.ethlo.lamebda.FunctionManagerDirector.lambda$setupDirectoryWatcher$0(FunctionManagerDirector.java:94)
	at com.ethlo.lamebda.io.WatchDir.processEvents(WatchDir.java:173)
	at com.ethlo.lamebda.FunctionManagerDirector$1.run(FunctionManagerDirector.java:110)
Caused by: java.io.EOFException: null
	at org.springframework.boot.loader.data.RandomAccessDataFile.read(RandomAccessDataFile.java:98)
	at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.load(CentralDirectoryFileHeader.java:78)
	at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.fromRandomAccessData(CentralDirectoryFileHeader.java:177)
	at org.springframework.boot.loader.jar.JarFileEntries.getEntry(JarFileEntries.java:323)
	... 26 common frames omitted
```

**Comment by ethlo** [comment] 2019-05-05 18:33
Thanks for the bug report! I, unfortunately, cannot reproduce this for version 0.9.1. Could you please verify that this is still reproducible on your end?

**Comment by ethlo** [comment] 2019-10-23 06:54
Still reproducible on 0.9.3

**Comment by ethlo** [comment] 2019-10-24 10:36
Fixed by expanding libraries into a temporary work directory

**Closed by ethlo** 2019-10-24 10:36 UTC

**Comment by khushbuv** [comment] 2020-05-13 12:28
Can anyone tell me what was the reason behind this issue?

**Comment by ethlo** [comment] 2020-05-15 09:00
The problem seemed to be that some classes can become referenced by the parent class loader and thus removing the file broke the open file pointers of that classloader.
